Repository wasmCloud/wasmCloud, pull requests merged in 2025-04, with the labels that each got.

#4332 fix: broken link.
  examples/typescript/components/http-hello-world/README.md
Labels: type:fix

#4327 fix(host): ignore auctions for builtin providers when disabled
  crates/host/src/wasmbus/ctl.rs
  crates/host/src/wasmbus/mod.rs
  crates/test-util/src/provider.rs
  tests/builtins.rs
Labels: scope:wasmcloud, type:fix

#4346 ci(nix): use pinned nixpkgs
  .github/actions/build-nix/action.yml
  .github/workflows/oci.yml
  .github/workflows/wasmcloud.yml
Labels: type:ci

#4297 fix(wash): use of no-arg plugins
  crates/wash/Cargo.toml
  crates/wash/src/bin/wash.rs
Labels: scope:wash, type:fix

#4361 [CI] Implemented a repo check on conventional-commit action to handle failed command
  .github/workflows/check-conventional-commits.yml
Labels: type:feature

#4091 chore(wash): adjust URL formatting in help
  crates/wash/src/cli/cmd/up.rs
  crates/wash/src/lib/config.rs
Labels: stale, scope:wash, type:fix

#4374 chore(wasmcloud): bump to 1.8.0 for release
  Cargo.lock
  Cargo.toml
Labels: scope:wasmcloud

#4383 ci: update action-gh-release to v2.2.2
  .github/workflows/secrets-nats-kv.yml
  .github/workflows/wash-plugins.yml
  .github/workflows/wasmcloud.yml
  .github/workflows/wit-wasmcloud-identity.yml
  .github/workflows/wit-wasmcloud-lattice-bus.yml
  .github/workflows/wit-wasmcloud-postgres.yml
  .github/workflows/wit-wasmcloud-secrets.yml
Labels: type:ci

#4392 ci(stalebot): remove
  .github/workflows/automate-stale.yml
Labels: type:ci

#4409 fix: remove azurecr.io publishing and references
  .github/workflows/examples-components.yml
  .github/workflows/oci.yml
  .github/workflows/provider.yml
  .github/workflows/secrets-nats-kv.yml
  .github/workflows/wasmcloud.yml
  crates/control-interface/src/client.rs
  crates/wash/build.rs
  crates/wash/src/cli/common/registry_cmd.rs
  crates/wash/src/cli/common/start_cmd.rs
  crates/wash/src/cli/ctl/mod.rs
  crates/wash/src/cli/par.rs
  crates/wash/src/lib/cli/claims.rs
  crates/wash/src/lib/cli/inspect.rs
  crates/wash/tests/wash_claims.rs
  crates/wash/tests/wash_inspect.rs
  crates/wash/tests/wash_par.rs
  crates/wash/tests/wash_reg.rs
  crates/wash/tools/README.md
  crates/wash/tools/kvcounter-example.sh
  examples/security/README.md
Labels: type:fix
