Repository wasmCloud/wasmCloud, pull requests merged in 2025-06, with the labels that each got.

#4535 ci(wash): Don't build throwaway files
  .github/workflows/wash.yml
Labels: scope:wash, type:ci

#4550 fix(keyvalue-redis): use default config for connection manager
  crates/provider-keyvalue-redis/src/lib.rs
  src/bin/keyvalue-redis-provider/wasmcloud.toml
Labels: type:fix

#4580 refactor(wash): remove duplicate constant for wadm.pid filename
  crates/wash/src/cli/cmd/up.rs
  crates/wash/src/cli/down/mod.rs
  crates/wash/src/lib/start/wadm.rs
  crates/wash/tests/start_wadm.rs
Labels: scope:wash

#4559 ci(nix): switch from vault to vault-bin package to speed-up flake
  flake.nix
Labels: type:ci

#4557 fix: add wasm-tools to dev dependencies for `wash`
  crates/wash/tools/deps_check.py
  flake.nix
Labels: type:fix

#4601 ci: ignore unspecified paths-filter paths
  .github/actions/install-cached-wash-cli/action.yml
  .github/workflows/wash.yml
  .github/workflows/wasmcloud.yml
Labels: type:ci
