Repository wasmCloud/wasmCloud, pull requests merged in 2025-05, with the labels that each got.

#4398 feat(host): track active component instances
  crates/host/src/metrics.rs
  crates/host/src/wasmbus/mod.rs
  crates/tracing/src/lib.rs
Labels: scope:wasmcloud, type:feature

#4440 chore(host): Reference wasmcloud_core::rpc helper methods consistently
  crates/host/src/nats/provider.rs
  crates/host/src/wasmbus/ctl.rs
  crates/host/src/wasmbus/providers/mod.rs
Labels: scope:wasmcloud

#4456 chore(wash): Address cargo clippy feedback
  crates/wash/src/cli/common/registry_cmd.rs
Labels: scope:wash

#4464 fix(examples): set default OTEL_EXPORTER_OTLP_ENDPOINT in docker-comp…
  examples/docker/docker-compose-full.yml
Labels: type:fix

#4472 feat(providers): improve http server error message
  crates/provider-http-server/src/address.rs
Labels: type:feature

#4473 fix(provider-kv-redis)!: search secrets first for default redis URL
  crates/provider-keyvalue-redis/src/lib.rs
Labels: impact:breaking, type:fix

#4475 feat(kv-provider-redis): enable disabling default connection
  crates/provider-keyvalue-redis/README.md
  crates/provider-keyvalue-redis/src/lib.rs
Labels: impact:breaking, type:fix, type:feature

#4480 feat(provider-kv-redis): support connection pooling
  Cargo.lock
  crates/provider-keyvalue-redis/Cargo.toml
  crates/provider-keyvalue-redis/README.md
  crates/provider-keyvalue-redis/src/lib.rs
Labels: type:fix, type:feature

#4488 chore(wash): update default host version to 1.8.0
  crates/wash/src/lib/common.rs
Labels: scope:wash

#4512 fix(examples): full OTEL-stack in docker-compose-full.yml
  examples/docker/docker-compose-full.yml
Labels: type:fix

#4527 fix(wash): windows build suffix
  crates/wash/src/lib/start/wasmcloud.rs
Labels: scope:wash, type:fix
