Repository wasmCloud/wasmCloud, pull requests merged in 2025-03, with the labels that each got.

#4188 feat(ci): Adds docker build the NATS KV secrets implementation
  .github/workflows/secrets-nats-kv.yml
  flake.nix
Labels: type:feature

#4189 fix(ci): Removes missed reference to wash-cli package
  .github/workflows/wasmcloud.yml
Labels: type:fix

#4190 fix(ci): Build nix binaries before image
  .github/workflows/secrets-nats-kv.yml
  crates/secrets-nats-kv/Cargo.toml
Labels: type:fix

#4197 ci(wash): release wash crate
  .github/workflows/wasmcloud.yml
Labels: scope:wash, type:ci

#4199 feat(blobby): modernize blobby with wasmcloud_component
  examples/rust/components/blobby/Cargo.toml
  examples/rust/components/blobby/src/lib.rs
Labels: type:feature

#4212 ci(checks): less eager commenting
  .github/workflows/check-conventional-commits.yml
Labels: type:ci

#4213 feature: host based http routing
  crates/provider-http-server/README.md
  crates/provider-http-server/src/host.rs
  crates/provider-http-server/src/lib.rs
Labels: type:feature

#4226 chore(host): Match non-workload identity first
  crates/host/src/wasmbus/mod.rs
Labels: scope:wasmcloud

#4225 chore(wash): Bump nats-server version to 2.10.26
  ci/manifests/wasmcloud/kustomization.yaml
  crates/wash/src/cli/cmd/up.rs
  crates/wash/src/lib/common.rs
  crates/wash/src/lib/start/mod.rs
  crates/wash/src/lib/start/nats.rs
Labels: scope:wash

#4244 fix(wash): Fixes wash tests on windows
  crates/wash/tests/common/mod.rs
  crates/wash/tests/wash_up.rs
Labels: scope:wash, type:fix

#4265 fix(nix): remove reference to nonexistent function
  flake.nix
Labels: type:fix

#4267 refactor!: Removes dependencies from host on provider libraries
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/http.rs
  crates/core/src/lib.rs
  crates/core/src/messaging.rs
  crates/host/Cargo.toml
  crates/host/src/wasmbus/providers/http_server/address.rs
  crates/host/src/wasmbus/providers/http_server/mod.rs
  crates/host/src/wasmbus/providers/messaging_nats.rs
  crates/provider-http-server/Cargo.toml
  crates/provider-http-server/src/address.rs
  crates/provider-http-server/src/lib.rs
  crates/provider-messaging-nats/Cargo.toml
  crates/provider-messaging-nats/src/connection.rs
  crates/provider-messaging-nats/src/lib.rs
  crates/provider-sdk/Cargo.toml
  crates/runtime/Cargo.toml
  crates/tracing/Cargo.toml
Labels: impact:breaking

#4271 chore(wash): Bump default versions to latest for wadm and host
  .github/workflows/examples-components.yml
  crates/wash/src/lib/common.rs
Labels: scope:wash

#4219 fix(providers): ensure prepared statements for pool clients
  crates/provider-sqldb-postgres/src/lib.rs
Labels: type:fix

#4289 feat(tracing): Adds support for resource attributes
  crates/host/src/wasmbus/providers/mod.rs
  crates/tracing/src/metrics.rs
  crates/tracing/src/traces.rs
Labels: type:feature

#4295 fix(docs): update links in prep for auto-copy
  crates/provider-sqldb-postgres/README.md
  examples/rust/components/http-blobstore/README.md
  examples/rust/components/messaging-image-processor-worker/README.md
  examples/rust/components/sqldb-postgres-query/README.md
  examples/rust/components/wadm-status-receiver/README.md
Labels: type:fix
