Repository wasmCloud/wasmCloud, pull requests merged in 2025-02, with the labels that each got.

#4097 ci(labeler): fix permissions
  .github/workflows/check-conventional-commits.yml
Labels: type:ci

#4103 ci(conventional-commits): avoid checkout on label
  .github/templates/conventional-commit.md
  .github/workflows/check-conventional-commits.yml
Labels: type:ci

#4128 fix(wasmcloud-platform): Correct certificate authorities configMap casing
  charts/wasmcloud-platform/templates/host-config.yaml
Labels: type:fix

#4140 ci: remove `host-sys` crate support
  .github/workflows/wasmcloud.yml
Labels: type:ci

#4142 test: log more in flaky `single_conn` test
  crates/provider-http-client/src/lib.rs
Labels: type:fix

#4159 ci: always upload `nix-store` artifact
  .github/actions/build-nix/action.yml
Labels: type:ci

#4143 docs(sqldb-postgres): missing POSTGRES_DATABASE
  crates/provider-sqldb-postgres/README.md
Labels: type:docs

#4163 ci(secrets-nats-kv): support crates.io release
  .github/workflows/secrets-nats-kv.yml
Labels: type:ci

#4110 feat(ci): Adds pipeline for running weekly benchmark test
  .github/workflows/benchmark.yml
  ci/README.md
  ci/common-env
  ci/delete-cluster.sh
  ci/manifests/cluster.yaml
  ci/manifests/machine-pools.yaml
  ci/manifests/patch.yaml
  ci/run-benchmarks.sh
  ci/setup-cluster-api.sh
Labels: type:feature

#4173 fix(ci): Ensure credentials are passed to cleanup step
  .github/workflows/benchmark.yml
Labels: type:fix
